// for join us from 
// categories
import {
  Camera,
  Video,
  Edit,
//   Image as ImageIcon,
  Users,
  Award,
  BookOpen,
  TrendingUp,
} from "lucide-react"; 

export  const roles = [
      {
    id: "team",
    icon: Users,
    title: "Production Team",
    description: "Collaborate with a full team for large-scale events",
  },
    {
      id: "cameraman",
      icon: Camera,
      title: "Cameraman",
      description: "Professional videographers and photographers",
    },
    {
      id: "editor",
      icon: Edit,
      title: "Video Editor",
      description: "Skilled post-production specialists",
    },
    {
      id: "equipment",
      icon: Video,
      title: "Equipment Partner",
      description: "Rent your professional gear to our clients",
    },
  ];

export   const experienceLevels = [
    {
      id: "experienced",
      title: "Experienced Professional",
      description: "Join our team with your existing skills",
      icon: Award,
    },
    {
      id: "moderate",
      title: "Moderate Experience",
      description: "Some experience with skill enhancement program",
      icon: TrendingUp,
    },
    {
      id: "fresher",
      title: "Fresher / New Graduate",
      description: "Start your career with our training program",
      icon: BookOpen,
    },
  ];


export const experiencedRequirements = {
  cameraman: [
    "3+ years of professional experience",
    "Proficiency with DSLR/Mirrorless cameras",
    "Knowledge of lighting and composition",
    "Experience with weddings, events, or commercials",
    "Own professional equipment (preferred)",
    "Reliable transportation",
    "Portfolio of previous work",
    "Client testimonials or references",
  ],
  editor: [
    "3+ years of video editing experience",
    "Proficiency in Adobe Premiere Pro/Final Cut Pro",
    "Color grading and audio mixing skills",
    "Motion graphics experience (After Effects)",
    "Fast turnaround capabilities",
    "Strong attention to detail",
    "Portfolio of edited projects",
    "Knowledge of various video formats",
  ],
  equipment: [
    "Professional-grade equipment inventory",
    "Well-maintained gear with documentation",
    "Insurance coverage for equipment",
    "Flexible rental availability",
    "Local pickup/delivery capability",
    "Competitive rental rates",
    "Equipment maintenance knowledge",
    "Business registration (preferred)",
  ],
  team: [
    "5+ years of combined team experience",
    "Specialized roles (cameramen, editors, coordinators)",
    "Proven track record with large-scale events",
    "Strong communication and coordination skills",
    "Ability to manage multiple shoots simultaneously",
    "Availability for travel and long-duration projects",
    "Comprehensive portfolio of team projects",
    "Client references showcasing teamwork efficiency",
  ],
};


export  const moderateRequirements = {
    cameraman: [
      "1-2 years of basic experience",
      "Basic knowledge of camera operations",
      "Some experience with events or personal projects",
      "Willingness to learn advanced techniques",
      "2-week skill enhancement program",
      "Mentorship from senior cameramen",
      "Portfolio development assistance",
      "Equipment training provided",
    ],
    editor: [
      "6 months to 1 year editing experience",
      "Basic knowledge of editing software",
      "Some personal or small project experience",
      "Eagerness to learn professional workflows",
      "2-week intensive training program",
      "Advanced software training",
      "Portfolio building assistance",
      "Industry standard workflow training",
    ],
    equipment: [
      "Some equipment or technical background",
      "Basic understanding of video gear",
      "Interest in equipment rental business",
      "Willingness to learn maintenance",
      "2-week equipment training program",
      "Business development guidance",
      "Partnership development support",
      "Marketing assistance provided",
    ],
    team: [
      "2-3 years of team coordination experience",
      "Basic project management skills",
      "Some experience leading small groups",
      "Willingness to learn advanced team management",
      "3-week team leadership training program",
      "Mentorship from senior production managers",
      "Project coordination practice",
      "Communication skills enhancement",
    ],
  };
export const fresherPrograms = {
  cameraman: [
    "6-week intensive camera training program",
    "Hands-on experience with professional equipment",
    "Mentorship from experienced cinematographers",
    "Portfolio development assistance",
    "Real wedding/event shooting experience",
    "Certification in video production",
    "2-month unpaid internship",
    "Guaranteed job placement after completion",
  ],
  editor: [
    "4-week video editing bootcamp",
    "Training in Adobe Creative Suite",
    "Color grading and motion graphics workshops",
    "Real project experience with client work",
    "Industry-standard workflow training",
    "Portfolio creation assistance",
    "2-month unpaid internship",
    "Job placement assistance",
  ],
  equipment: [
    "3-week equipment handling training",
    "Equipment maintenance and care workshops",
    "Business development support",
    "Insurance and legal guidance",
    "Marketing assistance for equipment rental",
    "Partnership development program",
    "2-month unpaid internship",
    "Revenue optimization strategies",
  ],
  team: [
    "4-week collaborative teamwork program",
    "Leadership and coordination workshops",
    "Hands-on experience with live event projects",
    "Mentorship from senior production teams",
    "Training in project and people management",
    "Certification in team management & collaboration",
    "2-month unpaid group internship",
    "Guaranteed placement in large-scale event projects",
  ],
}; 


export const benefits = {
  experienced: {
    cameraman: [
      "Competitive daily rates: ₹1000-5,000/day",
      "Performance bonuses up to ₹10,000/month",
      "Flexible scheduling and project selection",
      "Equipment provided for major projects",
      "Professional development workshops",
      "Regular work assignments guaranteed",
      "Health insurance coverage",
      "Annual equipment upgrade allowance",
    ],
    editor: [
      "Hourly rates: ₹200-1,000/hour",
      "Project completion bonuses",
      "Work-from-home flexibility",
      "Latest software licenses provided",
      "Skill development courses",
      "Priority project assignments",
      "Health and wellness benefits",
      "Annual performance incentives",
    ],
    equipment: [
      "Revenue sharing: 60-70% of rental income",
      "Equipment insurance coverage",
      "Marketing and promotion support",
      "Priority booking system",
      "Maintenance cost sharing",
      "Business development assistance",
      "Legal and contract support",
      "Expansion funding opportunities",
    ],
    team: [
      "Project-based compensation: ₹10,000-50,000/project",
      "Performance bonuses for large events",
      "Priority allocation for premium clients",
      "Dedicated project management support",
      "Team-building and leadership training",
      "Health and group insurance plans",
      "Annual international project opportunities",
      "Profit-sharing on long-term collaborations",
    ],
  },
  moderate: {
    cameraman: [
      "Starting rates: ₹500-3,000/day",
      "Free 2-week skill enhancement program",
      "Mentorship from senior professionals",
      "Equipment training and access",
      "Performance-based rate increases",
      "Career development pathway",
      "Health insurance after 3 months",
      "Guaranteed rate increase after 6 months",
    ],
    editor: [
      "Starting rates: ₹100-500/hour",
      "Free 2-week intensive training",
      "Advanced software training",
      "Portfolio development support",
      "Performance-based bonuses",
      "Skill certification programs",
      "Work-from-home options",
      "Rate progression plan",
    ],
    equipment: [
      "Revenue sharing: 50-60% of rental income",
      "Free 2-week equipment training",
      "Business development support",
      "Marketing assistance",
      "Equipment upgrade guidance",
      "Partnership development",
      "Insurance guidance",
      "Growth funding opportunities",
    ],
    team: [
      "Starting project rates: ₹5,000-20,000/project",
      "Free 3-week teamwork and coordination training",
      "Mentorship from senior production teams",
      "Access to advanced project management tools",
      "Career progression to lead positions",
      "Health insurance after 6 months",
      "Guaranteed project allocation after training",
      "Performance-linked bonuses",
    ],
  },
  fresher: {
    cameraman: [
      "Free 6-week comprehensive training",
      "Mentorship from industry professionals",
      "2-month unpaid internship with real projects",
      "Starting salary: ₹200-1,000/day after internship",
      "Career growth path to senior positions",
      "Certification upon completion",
      "Equipment training and access",
      "Job guarantee after successful completion",
    ],
    editor: [
      "Free 4-week intensive bootcamp",
      "Software training and licenses",
      "2-month unpaid internship with portfolio building",
      "Starting rate: ₹50-300/hour after internship",
      "Mentorship and skill development",
      "Industry networking opportunities",
      "Certification in video editing",
      "Guaranteed placement in our team",
    ],
    equipment: [
      "Free 3-week business training program",
      "Equipment handling and maintenance training",
      "2-month unpaid business development internship",
      "Partnership opportunities after completion",
      "Business setup assistance",
      "Insurance and legal guidance",
      "Marketing support and promotion",
      "Revenue sharing opportunities",
    ],
    team: [
      "Free 4-week collaborative training program",
      "Hands-on internship with live events",
      "Mentorship from senior production leads",
      "Starting stipend: ₹3,000-15,000/project after internship",
      "Certification in teamwork and production management",
      "Guaranteed placement in collaborative projects",
      "Career growth into specialized team roles",
      "Exposure to large-scale event production",
    ],
  },
};


export  const basicConditions = {
    experienced: [
      "Must pass practical skills assessment",
      "Provide portfolio and client references",
      "Own reliable transportation",
      "Professional communication skills",
      "Flexible schedule availability",
      "Commitment to quality standards",
      "Professional appearance and conduct",
      "Valid ID and business documentation",
    ],
    moderate: [
      "Complete 2-week skill enhancement program",
      "Pass practical and theoretical assessments",
      "Show willingness to learn and improve",
      "Maintain professional attitude",
      "Commit to 6-month minimum with company",
      "Attend all training sessions",
      "Accept mentorship and feedback",
      "Valid ID and basic documentation",
    ],
    fresher: [
      "Complete full training program (no dropouts)",
      "Maintain 90%+ attendance during training",
      "Successfully complete 2-month unpaid internship",
      "Pass final skills assessment",
      "Commit to 1-year minimum with company after training",
      "Professional attitude and eagerness to learn",
      "Basic computer and communication skills",
      "Valid ID and educational certificates",
    ],
  };

  
export   const skillOptions = {
    cameraman: [
      { id: "wedding-photography", label: "Wedding Photography" },
      { id: "event-videography", label: "Event Videography" },
      { id: "commercial-shoots", label: "Commercial Shoots" },
      { id: "drone-operation", label: "Drone Operation" },
      { id: "live-streaming", label: "Live Streaming" },
      { id: "portrait-photography", label: "Portrait Photography" },
      { id: "product-photography", label: "Product Photography" },
      { id: "fashion-photography", label: "Fashion Photography" },
      { id: "documentary-filming", label: "Documentary Filming" },
      { id: "music-video-production", label: "Music Video Production" },
      { id: "corporate-videography", label: "Corporate Videography" },
      { id: "sports-photography", label: "Sports Photography" },
      { id: "aerial-cinematography", label: "Aerial Cinematography" },
      { id: "underwater-photography", label: "Underwater Photography" },
      { id: "time-lapse-photography", label: "Time-lapse Photography" },
      { id: "macro-photography", label: "Macro Photography" },
    ],
    editor: [
      { id: "premiere-pro", label: "Adobe Premiere Pro" },
      { id: "after-effects", label: "After Effects" },
      { id: "final-cut-pro", label: "Final Cut Pro" },
      { id: "color-grading", label: "Color Grading" },
      { id: "motion-graphics", label: "Motion Graphics" },
      { id: "audio-editing", label: "Audio Editing" },
      { id: "davinci-resolve", label: "DaVinci Resolve" },
      { id: "avid-media-composer", label: "Avid Media Composer" },
      { id: "photoshop", label: "Adobe Photoshop" },
      { id: "illustrator", label: "Adobe Illustrator" },
      { id: "cinema-4d", label: "Cinema 4D" },
      { id: "blender", label: "Blender" },
      { id: "sound-design", label: "Sound Design" },
      { id: "vfx-compositing", label: "VFX Compositing" },
      { id: "animation", label: "2D/3D Animation" },
      { id: "subtitle-editing", label: "Subtitle Editing" },
    ],
    equipment: [
      { id: "camera-maintenance", label: "Camera Maintenance" },
      { id: "lighting-setup", label: "Lighting Setup" },
      { id: "audio-equipment", label: "Audio Equipment" },
      { id: "drone-equipment", label: "Drone Equipment" },
      { id: "rental-management", label: "Rental Management" },
      { id: "technical-support", label: "Technical Support" },
      { id: "lens-calibration", label: "Lens Calibration" },
      { id: "gimbal-operation", label: "Gimbal Operation" },
      { id: "live-streaming-setup", label: "Live Streaming Setup" },
      { id: "wireless-systems", label: "Wireless Systems" },
      { id: "backup-solutions", label: "Backup Solutions" },
      { id: "color-monitoring", label: "Color Monitoring" },
      { id: "power-management", label: "Power Management" },
      { id: "rigging-systems", label: "Rigging Systems" },
      { id: "transport-logistics", label: "Transport & Logistics" },
      { id: "insurance-handling", label: "Insurance Handling" },
    ],
    team: [
      { id: "project-management", label: "Project Management" },
      { id: "team-coordination", label: "Team Coordination" },
      { id: "event-planning", label: "Event Planning" },
      { id: "client-communication", label: "Client Communication" },
      { id: "budget-management", label: "Budget Management" },
      { id: "timeline-planning", label: "Timeline Planning" },
      { id: "quality-control", label: "Quality Control" },
      { id: "risk-management", label: "Risk Management" },
      { id: "vendor-coordination", label: "Vendor Coordination" },
      { id: "logistics-planning", label: "Logistics Planning" },
      { id: "crew-scheduling", label: "Crew Scheduling" },
      { id: "equipment-allocation", label: "Equipment Allocation" },
      { id: "safety-compliance", label: "Safety Compliance" },
      { id: "post-production-coordination", label: "Post-Production Coordination" },
      { id: "client-presentation", label: "Client Presentation" },
      { id: "team-training", label: "Team Training" },
    ],
  };

  export function generateMemberClientId(name, role) {
  const today = new Date();

  const nameShort = getShortName(name);
  const roleShort = getRoleShort(role);

  const month = String(today.getMonth() + 1).padStart(2, "0");
  const hh = String(today.getHours()).padStart(2, "0");
  const mm = String(today.getMinutes()).padStart(2, "0");

  return `${nameShort}${roleShort}-${month}-${hh}${mm}`;
}