// import type { Metadata } from "next";
// // import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { ThemeProvider } from "next-themes";


// import { AppProvider } from "@/contexts/AppContext";
// import { Toaster } from 'react-hot-toast'
// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className="">

//         <Toaster position="top-right" />
//         <AppProvider>
//     <ThemeProvider attribute="class">
//      <div  className="mt-32">
//       sas
//       <div className="dark:text-red-600 text-green-600">adsfsdf</div>
//      </div>
//           {children}
//     </ThemeProvider>
//         </AppProvider>

//       </body>
//     </html>
//   )
// }




import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { AppProvider } from "@/contexts/AppContext";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <AppProvider>
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
            <Toaster position="top-right" />
            {children}
          </ThemeProvider>
        </AppProvider>
      </body>
    </html>
  );
}



